Cloud hosted adjustments
OpenLiberty/draft-guide-kubernetes-microprofile-health pull request #107
Opened 2021-06-10 20:36 UTC by AustinSeto

2021-06-16 19:34 UTC, rutavshah reviewed
tested statically and passed

2021-06-16 20:25 UTC, AustinSeto commented
Now using common Kubernetes instructions, waiting on https://github.com/OpenLiberty/guides-common/pull/676 to be merged

2021-07-05 20:38 UTC, AustinSeto commented
Made changes similar to OpenLiberty/guide-kubernetes-intro#182 for accessing application on skills network

2021-07-20 17:48 UTC, AustinSeto commented
Issue on cloud hosted version, pods never enter ready state. Always shows `Ready 0/1`. Tested locally and pods start up fine.

2021-08-19 16:21 UTC, rutavshah approved these changes
LGTM

2021-08-19 20:54 UTC, dmuelle requested changes
a couple typos and some suggestions for concision and clarity

2021-08-19 20:54 UTC, dmuelle commented on README.adoc
> +// Staring and preparing your cluster for deployment
Staring--> Starting

2021-08-19 20:54 UTC, dmuelle commented on README.adoc
> +The liveness probes determine when a container needs to be restarted.
The liveness probes determine when a container needs to be restarted.
--->
The liveness probes determine whether a container needs to be restarted.

2021-08-19 20:54 UTC, dmuelle commented on README.adoc
> +Update the image names so that the images in your IBM Cloud container registry are used,
suggested edit

Update the image names so that the images in your IBM Cloud container registry are used.
Set the image pull policy to **Always** and remove the **nodePort** fields so that the ports are automatically generated

2021-08-19 20:54 UTC, dmuelle commented on README.adoc
> +This scenario can occur when the container has started,
suggested edit:

This scenario can occur when the container is started, but the application server isn't fully initialized.

2021-08-19 20:54 UTC, dmuelle commented on README.adoc
> +With the readiness probe, you can be certain the pod will only accept traffic
With the readiness probe, you can be certain the pod accepts traffic only
when the microservice is fully started.

2021-08-19 20:54 UTC, dmuelle commented on README.adoc
> +An endpoint has been provided under the **system** microservice to set it to an unhealthy
An endpoint is provided under the **system** microservice that sets it to an unhealthy 
state in the health check. The unhealthy state causes the readiness probe to fail.

2021-08-19 20:54 UTC, dmuelle commented on README.adoc
> +Observe that your request will still be successful because you have two replicas and one is still healthy.
Your request is successful because you have two replicas and one is still healthy.

2021-08-19 20:54 UTC, dmuelle commented on README.adoc
> +Observe that your request will still be successful because you have two replicas and one is still healthy.
Your request is successful because you have two replicas and one is still healthy.

2021-08-19 20:54 UTC, dmuelle commented on README.adoc
> +pod has been made unhealthy. You may see the same pod twice because there's a delay
...the second pod becomes unhealthy

2021-08-19 20:54 UTC, dmuelle commented on README.adoc
> +Therefore, traffic may still be routed to the unhealthy service for approximately 5 seconds.
Therefore, traffic may still be routed 
---->
Therefore, traffic might still be routed

2021-08-19 20:54 UTC, dmuelle commented on README.adoc
> +Observe it's no longer in the ready state either.
Observe that it's no longer in the ready state either.

2021-08-19 20:54 UTC, dmuelle commented on README.adoc
> +On a terminal, run the following POST request to make the first pod to not ready state.
From a terminal, run the following POST request to change the first pod to  a not-ready state.

2021-08-19 20:54 UTC, dmuelle commented on README.adoc
> +On a terminal, run the following POST requests to make the second pod to not ready state.
From a terminal, run the following POST request to change the first pod to  a not-ready state.

2021-08-19 20:54 UTC, dmuelle commented on README.adoc
> +Observe it's no longer in the ready state either.
Observe that it's no longer in the ready state either.

2021-08-19 20:54 UTC, dmuelle commented on README.adoc
> +If a test failure occurs, then you might have introduced a bug into the code.
If a test failure occurs
---->
If a test fails

2021-08-19 20:54 UTC, dmuelle commented on README.adoc
> +Go back to the terminals where you started the port forwarding the **system** service and
Go back to the terminals where you started the port forwarding the **system** service and 
the **inventory** service.
---->
Go back to the terminals where you started the port forwarding for the **system** service and 
the **inventory** service.

2021-08-20 14:46 UTC, AustinSeto commented
Thank you for the feedback @dmuelle, I've implemented all your suggestions, may you re-review?

2021-08-20 16:34 UTC, dmuelle approved these changes
LGTM

2021-08-20 17:15 UTC, gkwan-ibm requested changes
hold this PR

2021-08-20 17:26 UTC, dmuelle reviewed
a few edit suggestions

2021-08-20 17:26 UTC, dmuelle commented on README.adoc
> +Liveness probes are responsible for determining when a container needs to be restarted.
Readiness probes are responsible for determining that your application is ready to accept requests.
---->
Readiness probes determine whether your application is ready to accept requests.


Liveness probes are responsible for determining when a container needs to be restarted. 
--->
Liveness probes determine whether a container needs to be restarted.

2021-08-20 17:26 UTC, dmuelle commented on README.adoc
> +The readiness probe determines the READY status of the container as seen in the `kubectl get pods` output.
add comma

The readiness probe determines the READY status of the container, as seen in the `kubectl get pods` output.

2021-08-20 17:26 UTC, dmuelle commented on README.adoc
> +The [hotspot=delay1 hotspot=delay3]`initialDelaySeconds` field defines how long the probe should wait before it
defines how long the probe should wait
--->
defines how long the probe waits

2021-08-20 17:26 UTC, dmuelle commented on README.adoc
> +The [hotspot=threshold1 hotspot=threshold3]`failureThreshold` option defines how many times the probe should fail
The [hotspot=threshold1 hotspot=threshold3]`failureThreshold` option defines how many times the probe should fail before the state should be changed from ready to not ready.

---->

The [hotspot=threshold1 hotspot=threshold3]`failureThreshold` option defines how many times the probe fails before the state changes from ready to not ready.

2021-08-20 17:26 UTC, dmuelle commented on README.adoc
> +Without a readiness probe, you may notice an unsuccessful response from the server.
you may notice an unsuccessful response from the server.
--->
you might notice an unsuccessful response from the server.

2021-08-20 17:26 UTC, dmuelle commented on README.adoc
> +To run the tests, wait for all pods to be in the ready state before proceeding further.
To run the tests, wait for all pods to be in the ready state before proceeding further.
--->
Wait for all pods to be in the ready state before you run the tests.

2021-08-20 18:46 UTC, AustinSeto commented
@dmuelle implemented all the suggested changes, let me know what you think

2021-08-20 19:30 UTC, dmuelle approved these changes
LGTM

2022-05-18 17:03 UTC, closed without merging